[debug] [2020-06-12T06:52:30.091Z] ----------------------------------------------------------------------
[debug] [2020-06-12T06:52:30.096Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\jg036e\AppData\Roaming\npm\node_modules\firebase-tools\bin\firebase login --debug
[debug] [2020-06-12T06:52:30.097Z] CLI Version:   3.16.0
[debug] [2020-06-12T06:52:30.097Z] Platform:      win32
[debug] [2020-06-12T06:52:30.097Z] Node Version:  v13.9.0
[debug] [2020-06-12T06:52:30.102Z] Time:          Fri Jun 12 2020 12:22:30 GMT+0530 (India Standard Time)
[debug] [2020-06-12T06:52:30.102Z] ----------------------------------------------------------------------
[debug] 
[info] 
[info] Visit this URL on any device to log in:
[info] https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=713047797&redirect_uri=http%3A%2F%2Flocalhost%3A9005
[info] 
[info] Waiting for authentication...
[debug] [2020-06-12T06:52:45.471Z] >>> HTTP REQUEST POST https://accounts.google.com/o/oauth2/token  
 {
  code: '4/0wEha4GlLqYa3rAqy674Wap_o3CMZTm_kKUEE8vEhgpEEgVQlXyiVwBfLzzyb-ZXvDmf7XlwdWSn8UaRDtbCkkY',
  client_id: '563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com',
  client_secret: 'j9iVZfS8kkCEFUPaAeJV0sAi',
  redirect_uri: 'http://localhost:9005',
  grant_type: 'authorization_code'
} 
 Fri Jun 12 2020 12:22:45 GMT+0530 (India Standard Time)
[debug] [2020-06-12T06:52:53.788Z] Token Fetch Error: Error
    at new FirebaseError (C:\Users\jg036e\AppData\Roaming\npm\node_modules\firebase-tools\lib\error.js:11:17)
    at Request._callback (C:\Users\jg036e\AppData\Roaming\npm\node_modules\firebase-tools\lib\api.js:34:23)
    at self.callback (C:\Users\jg036e\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:185:22)
    at Request.emit (events.js:321:20)
    at Request.EventEmitter.emit (domain.js:485:12)
    at Request.onRequestError (C:\Users\jg036e\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:321:20)
    at ClientRequest.EventEmitter.emit (domain.js:485:12)
    at ClientRequest.onError (C:\Users\jg036e\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\tunnel-agent\index.js:179:21)
    at Object.onceWrapper (events.js:428:26)
[debug] [2020-06-12T06:56:15.731Z] ----------------------------------------------------------------------
[debug] [2020-06-12T06:56:15.734Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\jg036e\AppData\Roaming\npm\node_modules\firebase-tools\bin\firebase login
[debug] [2020-06-12T06:56:15.734Z] CLI Version:   3.16.0
[debug] [2020-06-12T06:56:15.734Z] Platform:      win32
[debug] [2020-06-12T06:56:15.734Z] Node Version:  v13.9.0
[debug] [2020-06-12T06:56:15.737Z] Time:          Fri Jun 12 2020 12:26:15 GMT+0530 (India Standard Time)
[debug] [2020-06-12T06:56:15.738Z] ----------------------------------------------------------------------
[debug] 
[info] 
[info] Visit this URL on any device to log in:
[info] https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=480522526&redirect_uri=http%3A%2F%2Flocalhost%3A9005
[info] 
[info] Waiting for authentication...
[debug] [2020-06-12T06:56:25.124Z] >>> HTTP REQUEST POST https://accounts.google.com/o/oauth2/token  
 {
  code: '4/0wFkYxfDX80cN4qspPknEPP6R4MYNcGNmbs3_g1DxApMenF3eCbao8naLUe5xEus4I_KGgO1L-RVTwZlE16zCmU',
  client_id: '563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com',
  client_secret: 'j9iVZfS8kkCEFUPaAeJV0sAi',
  redirect_uri: 'http://localhost:9005',
  grant_type: 'authorization_code'
} 
 Fri Jun 12 2020 12:26:25 GMT+0530 (India Standard Time)
[debug] [2020-06-12T06:56:33.410Z] Token Fetch Error: Error
    at new FirebaseError (C:\Users\jg036e\AppData\Roaming\npm\node_modules\firebase-tools\lib\error.js:11:17)
    at Request._callback (C:\Users\jg036e\AppData\Roaming\npm\node_modules\firebase-tools\lib\api.js:34:23)
    at self.callback (C:\Users\jg036e\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:185:22)
    at Request.emit (events.js:321:20)
    at Request.EventEmitter.emit (domain.js:485:12)
    at Request.onRequestError (C:\Users\jg036e\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:321:20)
    at ClientRequest.EventEmitter.emit (domain.js:485:12)
    at ClientRequest.onError (C:\Users\jg036e\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\tunnel-agent\index.js:179:21)
    at Object.onceWrapper (events.js:428:26)
[debug] [2020-06-12T06:58:14.688Z] ----------------------------------------------------------------------
[debug] [2020-06-12T06:58:14.692Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\jg036e\AppData\Roaming\npm\node_modules\firebase-tools\bin\firebase login --debug
[debug] [2020-06-12T06:58:14.692Z] CLI Version:   3.16.0
[debug] [2020-06-12T06:58:14.693Z] Platform:      win32
[debug] [2020-06-12T06:58:14.693Z] Node Version:  v13.9.0
[debug] [2020-06-12T06:58:14.696Z] Time:          Fri Jun 12 2020 12:28:14 GMT+0530 (India Standard Time)
[debug] [2020-06-12T06:58:14.697Z] ----------------------------------------------------------------------
[debug] 
[info] 
[info] Visit this URL on any device to log in:
[info] https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=1035685227&redirect_uri=http%3A%2F%2Flocalhost%3A9005
[info] 
[info] Waiting for authentication...
[debug] [2020-06-12T06:58:25.367Z] >>> HTTP REQUEST POST https://accounts.google.com/o/oauth2/token  
 {
  code: '4/0wF8q-hSyhKtnm_4CikDqx1cJ1kUqaZesX0OuWgUdYC_b-Ytilq1QuHXnQjFCFfoxkBmMa0KpKz-jRtET1c1uzs',
  client_id: '563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com',
  client_secret: 'j9iVZfS8kkCEFUPaAeJV0sAi',
  redirect_uri: 'http://localhost:9005',
  grant_type: 'authorization_code'
} 
 Fri Jun 12 2020 12:28:25 GMT+0530 (India Standard Time)
[debug] [2020-06-12T06:58:29.921Z] Token Fetch Error: Error
    at new FirebaseError (C:\Users\jg036e\AppData\Roaming\npm\node_modules\firebase-tools\lib\error.js:11:17)
    at Request._callback (C:\Users\jg036e\AppData\Roaming\npm\node_modules\firebase-tools\lib\api.js:34:23)
    at self.callback (C:\Users\jg036e\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:185:22)
    at Request.emit (events.js:321:20)
    at Request.EventEmitter.emit (domain.js:485:12)
    at Request.onRequestError (C:\Users\jg036e\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:321:20)
    at ClientRequest.EventEmitter.emit (domain.js:485:12)
    at ClientRequest.onError (C:\Users\jg036e\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\tunnel-agent\index.js:179:21)
    at Object.onceWrapper (events.js:428:26)
[debug] [2020-06-12T07:01:15.304Z] ----------------------------------------------------------------------
[debug] [2020-06-12T07:01:15.308Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\jg036e\AppData\Roaming\npm\node_modules\firebase-tools\bin\firebase login --debug
[debug] [2020-06-12T07:01:15.309Z] CLI Version:   3.16.0
[debug] [2020-06-12T07:01:15.309Z] Platform:      win32
[debug] [2020-06-12T07:01:15.310Z] Node Version:  v13.9.0
[debug] [2020-06-12T07:01:15.314Z] Time:          Fri Jun 12 2020 12:31:15 GMT+0530 (India Standard Time)
[debug] [2020-06-12T07:01:15.314Z] ----------------------------------------------------------------------
[debug] 
[info] 
[info] Visit this URL on any device to log in:
[info] https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=558924520&redirect_uri=http%3A%2F%2Flocalhost%3A9005
[info] 
[info] Waiting for authentication...
[debug] [2020-06-12T07:01:24.711Z] >>> HTTP REQUEST POST https://accounts.google.com/o/oauth2/token  
 {
  code: '4/0wGkd4KLMdZFoZhD3d4xWFdvwVRHJkTfCsLUurYZX5OD45JwEv8IdSzeLJSF_H0SMpn7emOrSzUeUquCZfAAMIY',
  client_id: '563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com',
  client_secret: 'j9iVZfS8kkCEFUPaAeJV0sAi',
  redirect_uri: 'http://localhost:9005',
  grant_type: 'authorization_code'
} 
 Fri Jun 12 2020 12:31:24 GMT+0530 (India Standard Time)
[debug] [2020-06-12T07:01:36.763Z] Token Fetch Error: Error
    at new FirebaseError (C:\Users\jg036e\AppData\Roaming\npm\node_modules\firebase-tools\lib\error.js:11:17)
    at Request._callback (C:\Users\jg036e\AppData\Roaming\npm\node_modules\firebase-tools\lib\api.js:34:23)
    at self.callback (C:\Users\jg036e\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:185:22)
    at Request.emit (events.js:321:20)
    at Request.EventEmitter.emit (domain.js:485:12)
    at Request.onRequestError (C:\Users\jg036e\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:321:20)
    at ClientRequest.EventEmitter.emit (domain.js:485:12)
    at ClientRequest.onError (C:\Users\jg036e\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\tunnel-agent\index.js:179:21)
    at Object.onceWrapper (events.js:428:26)
[debug] [2020-06-13T04:18:46.267Z] ----------------------------------------------------------------------
[debug] [2020-06-13T04:18:46.272Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\jg036e\AppData\Roaming\npm\node_modules\firebase-tools\bin\firebase login
[debug] [2020-06-13T04:18:46.273Z] CLI Version:   3.16.0
[debug] [2020-06-13T04:18:46.273Z] Platform:      win32
[debug] [2020-06-13T04:18:46.273Z] Node Version:  v13.9.0
[debug] [2020-06-13T04:18:46.281Z] Time:          Sat Jun 13 2020 09:48:46 GMT+0530 (India Standard Time)
[debug] [2020-06-13T04:18:46.281Z] ----------------------------------------------------------------------
[debug] 
[info] 
[info] Visit this URL on any device to log in:
[info] https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=250478166&redirect_uri=http%3A%2F%2Flocalhost%3A9005
[info] 
[info] Waiting for authentication...
[debug] [2020-06-13T04:19:14.026Z] >>> HTTP REQUEST POST https://accounts.google.com/o/oauth2/token  
 {
  code: '4/0wFpahVq1crhP6IAOOQ0E0cH2PNbePnW6SGpKliL4KGinV1oqWYHN91TxdBqkJWagtvbEgwYLVB-0Us8LfHDGck',
  client_id: '563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com',
  client_secret: 'j9iVZfS8kkCEFUPaAeJV0sAi',
  redirect_uri: 'http://localhost:9005',
  grant_type: 'authorization_code'
} 
 Sat Jun 13 2020 09:49:14 GMT+0530 (India Standard Time)
[debug] [2020-06-13T04:19:20.399Z] Token Fetch Error: Error
    at new FirebaseError (C:\Users\jg036e\AppData\Roaming\npm\node_modules\firebase-tools\lib\error.js:11:17)
    at Request._callback (C:\Users\jg036e\AppData\Roaming\npm\node_modules\firebase-tools\lib\api.js:34:23)
    at self.callback (C:\Users\jg036e\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:185:22)
    at Request.emit (events.js:321:20)
    at Request.EventEmitter.emit (domain.js:485:12)
    at Request.onRequestError (C:\Users\jg036e\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:321:20)
    at ClientRequest.EventEmitter.emit (domain.js:485:12)
    at ClientRequest.onError (C:\Users\jg036e\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\tunnel-agent\index.js:179:21)
    at Object.onceWrapper (events.js:428:26)
[debug] [2020-06-13T04:25:53.704Z] >>> HTTP REQUEST POST https://accounts.google.com/o/oauth2/token  
 {
  code: '4/0wE4uM9ZZa2jxgq1xTkSati0vUlYDTbNWzhZrF8KcA31iHI3SoPhpCi4ye8QsOHBmnbdGaJMyJNlTi6MfGMTisE',
  client_id: '563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com',
  client_secret: 'j9iVZfS8kkCEFUPaAeJV0sAi',
  redirect_uri: 'http://localhost:9005',
  grant_type: 'authorization_code'
} 
 Sat Jun 13 2020 09:55:53 GMT+0530 (India Standard Time)
[debug] [2020-06-13T04:26:03.103Z] Token Fetch Error: Error
    at new FirebaseError (C:\Users\jg036e\AppData\Roaming\npm\node_modules\firebase-tools\lib\error.js:11:17)
    at Request._callback (C:\Users\jg036e\AppData\Roaming\npm\node_modules\firebase-tools\lib\api.js:34:23)
    at self.callback (C:\Users\jg036e\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:185:22)
    at Request.emit (events.js:321:20)
    at Request.EventEmitter.emit (domain.js:485:12)
    at Request.onRequestError (C:\Users\jg036e\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:321:20)
    at ClientRequest.EventEmitter.emit (domain.js:485:12)
    at ClientRequest.onError (C:\Users\jg036e\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\tunnel-agent\index.js:179:21)
    at Object.onceWrapper (events.js:428:26)
[debug] [2020-06-13T04:28:12.067Z] >>> HTTP REQUEST POST https://accounts.google.com/o/oauth2/token  
 {
  code: '4/0wFiGb-_GeRww6y8LdPVx8HyKn2XUBrrcJ7Y-Pzv9vNTW0ptEB01jeKldIHMzo_2kaQi9HFotNO00oRmq3IbZ4k',
  client_id: '563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com',
  client_secret: 'j9iVZfS8kkCEFUPaAeJV0sAi',
  redirect_uri: 'http://localhost:9005',
  grant_type: 'authorization_code'
} 
 Sat Jun 13 2020 09:58:12 GMT+0530 (India Standard Time)
[debug] [2020-06-13T04:28:21.265Z] Token Fetch Error: Error
    at new FirebaseError (C:\Users\jg036e\AppData\Roaming\npm\node_modules\firebase-tools\lib\error.js:11:17)
    at Request._callback (C:\Users\jg036e\AppData\Roaming\npm\node_modules\firebase-tools\lib\api.js:34:23)
    at self.callback (C:\Users\jg036e\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:185:22)
    at Request.emit (events.js:321:20)
    at Request.EventEmitter.emit (domain.js:485:12)
    at Request.onRequestError (C:\Users\jg036e\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:321:20)
    at ClientRequest.EventEmitter.emit (domain.js:485:12)
    at ClientRequest.onError (C:\Users\jg036e\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\tunnel-agent\index.js:179:21)
    at Object.onceWrapper (events.js:428:26)
